payroll/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index),
    #emp
    url(r'^employer/?$', ViewListEmployer.as_view(), name='employer-list'),
    url(r'^employer/detail/(?P<pk>\d+)/$',ViewDetailEmployer.as_view(), name='employer-detail'),
    url(r'^employer/update/(?P<id>\d+)/$', ViewUpdateEmployer.as_view(), name='employer-update'),
    url(r'^employer/create/$', ViewCreateEmployer.as_view(), name='employer-create'),
    url(r'^employer/delete/(?P<pk>\d+)/$', DeleteEmploye, name='employer-delete'),

    #job
    url(r'^employer/(?P<class>\d+)/job/create$', CreateViewEmployerJobCreate.as_view(), name='employer-job'),
    url(r'^employer/job/(?P<pk>\d+)/$',ViewListJob.as_view(), name='job-list'),
    url(r'^job/update/(?P<id>\d+)/$', ViewUpdateJob.as_view(), name='job-update'),
    
    #kehadrian
    url(r'^attendance/?$',list_kehadiran, name='attendance-list'),
    url(r'^rekap-kehadiran/?$',rekap_kehadiran, name='rekap-kehadiran'),
    url(r'^attendance/user/?$',user_kehadiran, name='attendance-user'),

    #pengajian 
    url(r'^payroll/generate?$', view_generate_salary, name='payroll-generate'),
    url(r'^payroll/pay/(?P<pk>\d+)/$', Pay, name='payroll-pay'),


    url(r'^payroll/?$', ViewListPayroll.as_view(), name='payroll-list'),
    url(r'^payroll/detail/(?P<pk>\d+)/$',ViewDetailPayroll.as_view(), name='payroll-detail'),
    url(r'^allowance/?$', ViewListAllowance.as_view(), name='employer-list'),
    url(r'^allowance/detail/(?P<pk>\d+)/$',ViewDetailAllowance.as_view(), name='allowance-detail'),
    url(r'^allowance/update/(?P<id>\d+)/$', ViewUpdateAllowance.as_view(), name='allowance-update'),
    url(r'^allowance/create/$', ViewCreateAllowance.as_view(), name='allowance-create'),
    url(r'^allowance/delete/(?P<pk>\d+)/$', DeleteAllowance, name='employer-delete'),
    url(r'^pdf/(?P<pk>\d+)/', GeneratePdf.as_view(), name='pdf'),


    #izin 

    url(r'^izin/create/$', ViewCreateIzin.as_view(), name='izin-create'),
    url(r'^izin/$', ViewListIzin.as_view(), name='izin-list'),
    url(r'^izin/approval/(?P<pk>\d+)/$', izin_approval, name='izin-approval'),
    url(r'^izin/employer/$', ViewListIzinEmployer.as_view(), name='izin-employer'),
     
    #cuti
    url(r'^cuti/?$', ViewListCuti.as_view(), name='cuti-list'),
    url(r'^cuti/pengajuan?$', ViewPengajuanCuti.as_view(), name='cuti-pengajuan'),
    url(r'^cuti/create?$', ViewCreateCuti.as_view(), name='cuti-create'),
    url(r'^cuti/approval/(?P<pk>\d+)/$', cuti_approval, name='cuti-approval'),
    url(r'^cuti/employer/$', ViewPengajuanCutiEmployer.as_view(), name='cuti-employer'),


    #
    url(r'^login/?$',login_page, name='login'),
     url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models import signals
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser


class Employer(models.Model) :

    GENDER_CHOICES  = (
        ('M','Male'),
        ('F','Female')
    )

    STATUS_PAJAK  = (
        ('k0','k0'),
        ('k1','k1'),
        ('k2','k2'),
        ('k3','k3'),
        ('tk0','tk0'),
        ('tk1','tk1'),
        ('tk2','tk2'),
        ('tk3','tk3')
    )

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=2,choices=GENDER_CHOICES)
    no_ktp = models.CharField(max_length=20)
    born_date = models.DateField()
    bron_place = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    address = models.TextField()
    email = models.EmailField()
    last_education = models.CharField(max_length=200)
    educational_institution = models.CharField(max_length=200)
    major = models.CharField(max_length=200)
    no_npwp = models.CharField(max_length=50)
    status_pajak = models.CharField(max_length=10,choices=STATUS_PAJAK)
    no_bank = models.CharField(max_length=50)
    name_bank = models.CharField(max_length=100)
    account_name_bank = models.CharField(max_length=200)    
    photo = models.FileField(max_length=200)
    pin=models.CharField(max_length=20)
    tgl_kerja = models.DateField(default=datetime.now, blank=True)

    @property
    def position(self):
        return self.job_set.filter(active=True).first()


    @property
    def jobCount(self):
        return self.job_set.count()


    def __str__(self):
        return self.name


# @receiver(signals.pre_save, sender=Employer)
# def create_employer(sender, **kwargs):
    
#     print kwargs['instance'].pk
#     user = User.objects.create_user(
#             email=kwargs['instance'].email,
#             username=kwargs['instance'].email,
#             password="123456",
#             is_employer=True,
#             employer_id =  kwargs['instance'].pk
#         )


class User(AbstractUser):
    is_employer = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    employer_id = models.IntegerField()



class Job(models.Model) :
    id = models.AutoField(primary_key=True)
    position = models.CharField(max_length=200)
    employer = models.ForeignKey(Employer,on_delete=models.CASCADE)
    salary = models.IntegerField()
    start_date = models.DateField()
    active = models.BooleanField()

    
    def __str__(self):
       return self.position



class AttendanceList(models.Model) :

    id = models.AutoField(primary_key=True)
    date = models.DateTimeField()
    employer = models.ForeignKey(Employer,on_delete=models.CASCADE)
    status = models.CharField(max_length=20)


class Allowance(models.Model)  :

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    amount = models.IntegerField(null=True)


class SalarySlip(models.Model) :

    id = models.AutoField(primary_key=True)
    employer = models.ForeignKey(Employer,on_delete=models.CASCADE)
    date = models.DateTimeField()
    payment_status = models.BooleanField(default=False)
    total_income = models.IntegerField()
    total_deduction = models.IntegerField()
    month = models.IntegerField()
    year = models.IntegerField()
    total_pay = models.IntegerField()

    @property
    def income(self):
        return self.income_set.all()

    @property
    def deduction(self):
        return self.deduction_set.all()



class Income(models.Model) :
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    unit = models.IntegerField()
    total = models.IntegerField()
    salaryslip = models.ForeignKey(SalarySlip,on_delete=models.CASCADE)

class Deduction(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    unit = models.IntegerField()
    total = models.IntegerField()
    salaryslip = models.ForeignKey(SalarySlip,on_delete=models.CASCADE)


class Cuti(models.Model) :
    id = models.AutoField(primary_key=True)
    employer = models.ForeignKey(Employer,on_delete=models.CASCADE)
    start = models.DateTimeField()
    end = models.DateTimeField()
    quota = models.IntegerField()
    take = models.IntegerField()



class ScanLog(models.Model) :
    id = models.AutoField(primary_key=True)
    sn=models.CharField(max_length=200)
    scan_date =models.DateTimeField()
    pin=models.CharField(max_length=10)
    verifymode=models.IntegerField()
    iomode=models.IntegerField()
    workcode=models.IntegerField()
    cekin=models.CharField(max_length=10)
    cekout=models.CharField(max_length=10)


class Holidays(models.Model) :
    id = models.AutoField(primary_key=True)
    date = models.DateField()
    name = models.CharField(max_length=200)


class StatusPajak(models.Model) :
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    amount = models.IntegerField()


class Izin(models.Model) :

    GENDER_CHOICES  = (
        ('I','Izin'),
        ('S','Sakit')
    )
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=2,choices=GENDER_CHOICES)
    date = models.CharField(max_length=200)
    keterangan = models.CharField(max_length=200)
    surat = models.FileField(upload_to='documents/',default=None, blank=True, null=True)
    status = models.BooleanField(default=False)
    employer = models.ForeignKey(Employer,on_delete=models.CASCADE)


class Option(models.Model) :
     id = models.AutoField(primary_key=True)
     cuti = models.ImageField()
     

class JatahCuti(models.Model) :
    id = models.AutoField(primary_key=True)
    employer = models.ForeignKey(Employer,on_delete=models.CASCADE)
    start = models.DateField()
    end = models.DateField()
    quota = models.IntegerField()
    take = models.IntegerField()

    @property
    def sisa(self):
        return self.quota-self.take



class PengajuanCuti(models.Model) :
    id = models.AutoField(primary_key=True)
    date = models.CharField(max_length=200)
    keterangan = models.CharField(max_length=200)
    status = models.BooleanField(default=False)
    employer = models.ForeignKey(Employer,on_delete=models.CASCADE)

payroll/forms.py
from django import forms
from .models import  Employer,Job,Allowance,Izin,PengajuanCuti
from django.forms import ModelForm


class DateInput(forms.DateInput):
    input_type = 'date'


class EmployerForm(ModelForm):

    class Meta:
        model = Employer
        fields = [
            'name',
            'gender',
            'no_ktp',
            'born_date',
            'bron_place',
            'phone',
            'address',
            'email',
            'last_education',
            'educational_institution',
            'major',
            'no_npwp',
            'status_pajak',
            'no_bank',
            'name_bank',
            'account_name_bank',
            'pin',
            'status_pajak'
        ]

        widgets = {
            'born_date': DateInput()
        }


class JobForm(ModelForm) :

    class Meta :
        model = Job
        fields = [
            'position',
            'salary',
            'start_date'
        ]

        widgets = {
            'start_date': DateInput()
        }


class AllowanceForm(ModelForm) :

    class Meta :
        model = Allowance
        fields = [
            'name',
            'amount',
        ]


class IzinForm(ModelForm) :
    surat = forms.FileField(required=False)

    class Meta :
        model = Izin
        fields = [
            'type',
            'date',
            'keterangan',
            'surat'
        ]


class CutiForm(ModelForm) :
    
    class Meta :
        model = PengajuanCuti
        fields = [
            'date',
            'keterangan',
        ]


class LoginForm(forms.Form) :
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

payroll/templates/izin/create.html
{% extends "base.html" %}


{% block content %}
{% load widget_tweaks %}
<div class="container-fluid">
    <div class="row">
            <div class="col-md-12">
                <div class="panel ">
                    <div class="panel-body panel-form"> 
                        <form action=""  method="post"   enctype="multipart/form-data" class="form-horizontal">
                            {% csrf_token %}
                            <div class="col-md-8 ">
                                    <div class="row ">
                                            <div class="col-xs-12">
                                                <h4 >Pengajuan Izin/Sakit</h4>
                                                <hr>
                                            </div>
                                            <div class="form-group">
                                                <label for="" class="col-md-4 control-label"><span class="bintang text-danger">* </span>
                                                    Tagal Izin
                                                </label>
                                                <div class="col-md-8">
                                                    {{ form.date |add_class:"form-control" }}

                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="" class="col-md-4 control-label"><span class="bintang text-danger">* </span>
                                                    Type
                                                </label>
                                                <div class="col-md-8">
                                                    {{ form.type |add_class:"form-control" }}
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="" class="col-md-4 control-label">
                                                    Surat
                                                </label>
                                                <div class="col-md-8">
                                                    {{ form.surat |add_class:"form-control" }}
                                                </div>
                                            </div>       
                                            <div class="form-group">
                                                <label for="" class="col-md-4 control-label"><span class="bintang text-danger">* </span>
                                                    Keterangan
                                                </label>
                                                <div class="col-md-8">
                                                    {{ form.keterangan |add_class:"form-control" }}
                                                </div>
                                            </div>       
                                            
                                            <div class="form-group">
                                                    <div class="col-xs-12">
                                                        <div class="pull-right">
                                                            <button class="btn btn-warning btn-sm" type="submit">
                                                                Simpan                                      </button>
                                                            <a href="/employer">
                                                                <button class="btn btn-danger btn-sm" type="button">Batal</button>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>

                                    </div>
                            </div>
                        </form>
                </div>
        </div>
    </div>
</div>

{% endblock  %}



{% block js %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script>
    $('input[name="date"]').daterangepicker();

    $( document ).ready(function() {
        $('#id_type').change(function() {
            if(this.value == 'S'){
                $("#id_surat").prop('required',true);
            }
        });
      });
</script>
{% endblock  %}

payroll/templates/izin/list-emp.html
{% extends "base.html" %}

{% block modal %}
<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade" id="imagemodal" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="myModalLabel">Image preview</h4>
            </div>
            <div class="modal-body">
              <img src="" id="imagepreview" style="width: 400px; height: 264px;" >
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
</div>
{% endblock  %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">
                            Pengajuan Izin/Sakit
                        </h4>
                    </div>
                    <div class="content table-responsive table-full-width">
                        <table class="table table-striped">
                            <thead>
                                <th>Tgl Izin</th>
                                <th>Type</th>
                                <th>Surat</th>
                                <th>Status</th>
                            </thead>
                            <tbody>
                                {% for izin in object_list %}
                                <tr>
                                    <td>{{izin.date}}</td>
                                    <td>{{izin.type}}</td>
                                    <td>
                                        <button data-image="/media/{{izin.surat}}"  type="button" class="btn btn-info pop">Lihat</button>
                                    </td>
                                    <td>
                                        {% if izin.status %}
                                        Disetujui
                                        {% else %}
                                        Belum
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


{% endblock  %}



{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.0.7/sweetalert2.all.min.js"></script>
<script>
        $( document ).ready(function() {
            $(".pop").on("click", function() {
                var image = $(this).attr('data-image');
                $('#imagepreview').attr('src',image);
                $('#imagemodal').modal('show');

             });
        });
        function checkDelete(id) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                $.ajax({
                    url:"/employer/delete/"+id,
                    type: 'GET',
                })
                .done(function(res) {
                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                    location.reload();
                })
            }
        })
        }
    </script>

{% endblock  %}

payroll/templates/izin/list.html
{% extends "base.html" %}

{% block modal %}
<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade" id="imagemodal" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="myModalLabel">Image preview</h4>
            </div>
            <div class="modal-body">
              <img src="" id="imagepreview" style="width: 400px; height: 264px;" >
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
</div>
{% endblock  %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">
                            Pengajuan Izin/Sakit
                        </h4>
                    </div>
                    <div class="content table-responsive table-full-width">
                        <table class="table table-striped">
                            <thead>
                                <th>Tgl Izin</th>
                                <th>Karyawan</th>
                                <th>Type</th>
                                <th>Surat</th>
                                <th>Status</th>
                            </thead>
                            <tbody>
                                {% for izin in object_list %}
                                <tr>
                                    <td>{{izin.date}}</td>
                                    <td>{{izin.employer.name}}</td>
                                    <td>{{izin.type}}</td>
                                    <td>
                                        <button data-image="/media/{{izin.surat}}"  type="button" class="btn btn-info pop">Lihat</button>
                                    </td>
                                    <td>
                                        {% if izin.status %}
                                        Disetujui
                                        {% else %}
                                        <a  href="{% url 'izin-approval' izin.id %}" type="button" class="btn btn-info">Setujui</a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


{% endblock  %}



{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.0.7/sweetalert2.all.min.js"></script>
<script>
        $( document ).ready(function() {
            $(".pop").on("click", function() {
                var image = $(this).attr('data-image');
                $('#imagepreview').attr('src',image);
                $('#imagemodal').modal('show');

             });
        });
        function checkDelete(id) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                $.ajax({
                    url:"/employer/delete/"+id,
                    type: 'GET',
                })
                .done(function(res) {
                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                    location.reload();
                })
            }
        })
        }
    </script>

{% endblock  %}